version: '2'

services:
  webserver:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public_html:/usr/share/nginx/html
    links:
      - db
      - php-fpm

  php-fpm:
    image: php:7.0.4-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./public_html:/usr/share/nginx/html
    links:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=db_jasen
